# Generated by Django 3.2.9 on 2021-11-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_stars', models.IntegerField()),
            ],
            options={
                'db_table': 'song_album',
            },
        ),
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'song_category',
            },
        ),
        migrations.CreateModel(
            name='SongChords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(default=None, upload_to='')),
                ('chords', models.TextField(default='')),
                ('sample_rate', models.IntegerField(default=0)),
                ('song_lyric', models.TextField(default='')),
                ('song_chord_type', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchords.songalbum')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchords.songcategory')),
            ],
            options={
                'db_table': 'song_chords',
            },
        ),
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'song_genre',
            },
        ),
        migrations.CreateModel(
            name='SongMusician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aditional_info', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'song_musician',
            },
        ),
        migrations.CreateModel(
            name='SongPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchords.songchords')),
            ],
            options={
                'db_table': 'song_playlist',
            },
        ),
        migrations.AddField(
            model_name='songchords',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchords.songgenre'),
        ),
        migrations.AddField(
            model_name='songalbum',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getchords.songmusician'),
        ),
    ]
