# Generated by Django 3.2.9 on 2021-12-26 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getchords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songchords',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='songchords',
            name='mod_date',
            field=models.DateTimeField(null=True),
        ),
    ]
